version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
    working_directory: /go/src/github.com/moznion/bigbinary-go
    steps:
      - checkout
      - run: make bootstrap
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)

